print("taller AIPython")
print()
print("hola","soy","Carlos")
print('prueba separador','funcion sep',sep="*")
print("probando argumentos","soy el segundo argumento",end='-')
print('soy otra linea 6')
print('soy linea 7')
print(type(40))
print((40+9))
print((40+9)/2)